# Generated by Django 3.2.15 on 2023-02-09 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_ordermenuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermenuitem',
            name='availability',
        ),
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='сумма заказа'),
        ),
        migrations.AddField(
            model_name='ordermenuitem',
            name='count',
            field=models.IntegerField(db_index=True, default=1, verbose_name='количество'),
        ),
    ]
