# Generated by Django 3.2.15 on 2023-02-09 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230209_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermenuitem',
            options={'verbose_name': 'пункт заказа', 'verbose_name_plural': 'пункты заказа'},
        ),
        migrations.AddField(
            model_name='ordermenuitem',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, verbose_name='адрес'),
        ),
        migrations.AlterUniqueTogether(
            name='ordermenuitem',
            unique_together={('order', 'product')},
        ),
    ]
