# Generated by Django 3.2.15 on 2023-02-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20230209_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermenuitem',
            old_name='count',
            new_name='quantity',
        ),
    ]
