# Generated by Django 3.2.15 on 2023-02-12 16:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230212_2234'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('order_cost', django.db.models.manager.Manager()),
            ],
        ),
    ]
