# Generated by Django 3.2.15 on 2023-02-13 05:23

from django.db import migrations


def change_price(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Product = apps.get_model('foodcartapp', 'Product')
    OrderMenuItem = apps.get_model('foodcartapp', 'OrderMenuItem')

    for order in Order.objects.all():
        for order_item in order.order_items.all():
            order_product = Product.objects.get(id=order_item.product.id)
            if order_product:
                order_item.price = order_product.price
                order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_ordermenuitem_price'),
    ]

    operations = [
        migrations.RunPython(change_price)
    ]
