# Generated by Django 3.2.15 on 2023-02-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230213_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'необработанный'), ('AS', 'сборка'), ('DL', 'доставка'), ('FN', 'исполнен')], db_index=True, default='PR', max_length=2, verbose_name='статус заказа'),
        ),
    ]
