# Generated by Django 3.2.15 on 2023-02-13 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='regisred_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Время регистрации'),
        ),
    ]
