# Generated by Django 3.2.15 on 2023-02-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20230213_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('наличностью', 'наличностью'), ('электронно', 'электронно')], db_index=True, default='наличностью', max_length=12, verbose_name='Способ оплаты'),
        ),
    ]
